### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bkzutr90** [IshanJ25/Stickoz-for-WhatsApp#12]
:~/WA_sticker_formatting# python whatsapp_sticker_maker.py
  File "whatsapp_sticker_maker.py", line 37
    def make_stickers(folder: str = None, output_folder: str = None, animated: bool = False, empty_if_contents=False, save_as_webp=False):
                            ^
SyntaxError: invalid syntax

**Comment by IshanJ25** [comment]
Could you please provide the steps to reproduce this error?
As is, what all steps did you take before encountering this error?

**Comment by bkzutr90** [comment]
I just git clone and run the .py 
and then that result syntax error

**Comment by IshanJ25** [comment]
okay, could you give me some software specs?
Like OS and python version

**Comment by bkzutr90** [comment]
I'm using Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-131-generic x86_64) on VPS
and Python 3.8.10

**Comment by IshanJ25** [comment]
Here are some points I can suggest for troubleshooting:

 - re-run the script
 - restart your system or VPS and try again
 - check if the dependencies are installed, as found in `requirements.txt`
 - the `whatsapp_sticker_maker.py` is just like a python package, do not run it. Just use it to import the function, as shown in the example
 - make your preferred changes in the `example.py` following the [Usage ](https://github.com/IshanJ25/WA_sticker_formatting#parameters)and [Parameters](https://github.com/IshanJ25/WA_sticker_formatting#parameters) and then run that file.

Please try these steps and see if it helps you

**Comment by IshanJ25** [comment]
@bkzutr90 just a follow up
Is it functional now?

**Comment by IshanJ25** [comment]
I am closing this issue for now, if you face the same problem in the future, you can reopen the issue.
